// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hcdapsriszvdiueqxygs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhjZGFwc3Jpc3p2ZGl1ZXF4eWdzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkxODUxODIsImV4cCI6MjA1NDc2MTE4Mn0.1owKqWuocnI03JVwth8sIJEeqY59iz-EjJp24wyz-_U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);